[workspace]
members = [
    "zlib-rs",
    "libz-rs-sys",
    "load-dynamic-libz-ng",
]
exclude = [ ]

# Without the `-p` flag, cargo ignores `--no-default-features` when you have a
# workspace, and without `resolver = "2"` here, you can't use `-p` like this.
resolver = "2"

# Global settings for our crates
[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Zlib"
repository = "https://github.com/memorysafety/zlib-rs"
homepage = "https://github.com/memorysafety/zlib-rs"
readme = "./README.md"
description = "A memory-safe zlib implementation written in rust"
publish = true
rust-version = "1.70" # MSRV

[profile.release]
debug = true

[profile.dev]
opt-level = 1 # required for the tail calls in inflate to optimize

[workspace.dependencies]
libloading = "0.8.1"
libz-sys = { version = "1.1.12", default-features = false, features = ["zlib-ng"] } # use libz-ng in libz compat mode
arbitrary = { version = "1.0" }

libc = "0.2.153" # TODO remove

zlib-rs = { version = "0.1.0", path = "./zlib-rs" }
load-dynamic-libz-ng = { path = "./load-dynamic-libz-ng" }

