[package]
name = "dynamic-libz-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading.workspace = true

[features]
libc = []


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(zng)'] }
